/**
 * HṚṢĪKEŚA (हृषीकेश) — Built-in Core Skills
 *
 * Phase 20: 8 Initial Safe Built-in Procedural Skills
 */

import { SkillDefinition } from '../interfaces/skill.types.js';
import { ENGINEERING_SKILLS } from '../../engineering/skills/engineering.skills.js';

export const BUILTIN_SKILLS: SkillDefinition[] = [
  // 1. inspect-project
  {
    id: 'builtin-inspect-project',
    name: 'inspect-project',
    displayName: 'Inspect Project Structure',
    description: 'Inspects directory structure, configuration files, and project health indicators.',
    category: 'SOFTWARE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['inspect project', 'check repository', 'project structure', 'inspect repo'],
    requiredCapabilities: ['filesystem', 'code-analysis'],
    requiredTools: ['file_list', 'file_read'],
    inputsSchema: {
      type: 'object',
      properties: {
        directory: { type: 'string', default: '.' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        summary: { type: 'string' },
        fileCount: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'list_files',
        name: 'List Workspace Files',
        stepType: 'TOOL',
        tool: 'file_list',
        dependencies: [],
        inputs: { path: '.' },
        timeoutMs: 30000,
      },
      {
        stepIndex: 1,
        stepId: 'read_manifest',
        name: 'Read Project Manifest',
        stepType: 'TOOL',
        tool: 'file_read',
        dependencies: ['list_files'],
        inputs: { path: 'package.json' },
        timeoutMs: 30000,
      },
      {
        stepIndex: 2,
        stepId: 'verify_structure',
        name: 'Verify Project Validity',
        stepType: 'VERIFY',
        dependencies: ['read_manifest'],
        verification: {
          type: 'file_exists',
          target: 'package.json',
        },
        timeoutMs: 10000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['filesystem', 'code-analysis'],
      requiredTools: ['file_list', 'file_read'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 2. analyze-code
  {
    id: 'builtin-analyze-code',
    name: 'analyze-code',
    displayName: 'Analyze Code Quality',
    description: 'Inspects source code for quality, TypeScript type safety, and formatting standards.',
    category: 'SOFTWARE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['analyze code', 'check code quality', 'code analysis', 'review code'],
    requiredCapabilities: ['code-analysis', 'filesystem'],
    requiredTools: ['file_read'],
    inputsSchema: {
      type: 'object',
      properties: {
        targetFile: { type: 'string' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        passed: { type: 'boolean' },
        findings: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'read_source',
        name: 'Read Target Source Code',
        stepType: 'TOOL',
        tool: 'file_read',
        dependencies: [],
        timeoutMs: 30000,
      },
      {
        stepIndex: 1,
        stepId: 'analyze_ast',
        name: 'Analyze AST and Structure',
        stepType: 'MODEL',
        dependencies: ['read_source'],
        timeoutMs: 60000,
      },
      {
        stepIndex: 2,
        stepId: 'verify_analysis',
        name: 'Verify Analysis Findings',
        stepType: 'VERIFY',
        dependencies: ['analyze_ast'],
        verification: {
          type: 'custom',
          target: 'analysis_complete',
        },
        timeoutMs: 10000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['code-analysis', 'filesystem'],
      requiredTools: ['file_read'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 3. run-tests
  {
    id: 'builtin-run-tests',
    name: 'run-tests',
    displayName: 'Run Test Suite',
    description: 'Executes automated tests and verifies assertion outcomes.',
    category: 'DEVOPS',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['run tests', 'execute test suite', 'run unit tests', 'run checks'],
    requiredCapabilities: ['terminal', 'testing'],
    requiredTools: ['terminal_execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        testFilter: { type: 'string' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        passed: { type: 'boolean' },
        exitCode: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'execute_test_cmd',
        name: 'Execute Test Command',
        stepType: 'TOOL',
        tool: 'terminal_execute',
        dependencies: [],
        inputs: { command: 'npm test' },
        timeoutMs: 120000,
      },
      {
        stepIndex: 1,
        stepId: 'verify_test_success',
        name: 'Verify Zero Exit Code',
        stepType: 'VERIFY',
        dependencies: ['execute_test_cmd'],
        verification: {
          type: 'command_exit_code',
          target: 'npm test',
          expectedValue: 0,
        },
        timeoutMs: 10000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['terminal', 'testing'],
      requiredTools: ['terminal_execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 4. research-topic
  {
    id: 'builtin-research-topic',
    name: 'research-topic',
    displayName: 'Research Topic Intelligence',
    description: 'Conducts evidence-backed research, verifies sources, and extracts structured facts.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['research topic', 'research company', 'market research', 'investigate topic'],
    requiredCapabilities: ['web', 'research', 'knowledge-write'],
    requiredTools: ['web_search', 'web_scrape'],
    inputsSchema: {
      type: 'object',
      properties: {
        topic: { type: 'string' },
        depth: { type: 'string', default: 'standard' },
      },
      required: ['topic'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        report: { type: 'string' },
        sources: { type: 'array' },
        evidence: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'search_sources',
        name: 'Search Web Sources',
        stepType: 'RESEARCH',
        capability: 'research',
        dependencies: [],
        timeoutMs: 45000,
      },
      {
        stepIndex: 1,
        stepId: 'extract_evidence',
        name: 'Extract Evidence & Quotes',
        stepType: 'RESEARCH',
        capability: 'research',
        dependencies: ['search_sources'],
        timeoutMs: 45000,
      },
      {
        stepIndex: 2,
        stepId: 'synthesize_findings',
        name: 'Synthesize Findings',
        stepType: 'MODEL',
        dependencies: ['extract_evidence'],
        timeoutMs: 60000,
      },
      {
        stepIndex: 3,
        stepId: 'verify_citations',
        name: 'Verify Primary Citations',
        stepType: 'VERIFY',
        dependencies: ['synthesize_findings'],
        verification: {
          type: 'custom',
          target: 'citations_verified',
        },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web', 'research', 'knowledge-write'],
      requiredTools: ['web_search', 'web_scrape'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'COMPANY', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 5. create-local-file
  {
    id: 'builtin-create-local-file',
    name: 'create-local-file',
    displayName: 'Create Local File',
    description: 'Writes safe, deterministic content to an authorized local workspace file.',
    category: 'COMPUTER',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['create file', 'write file', 'create local file', 'save file'],
    requiredCapabilities: ['filesystem'],
    requiredTools: ['file_write'],
    inputsSchema: {
      type: 'object',
      properties: {
        path: { type: 'string' },
        content: { type: 'string' },
      },
      required: ['path', 'content'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        success: { type: 'boolean' },
        filePath: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'write_file',
        name: 'Write File to Disk',
        stepType: 'TOOL',
        tool: 'file_write',
        dependencies: [],
        timeoutMs: 30000,
      },
      {
        stepIndex: 1,
        stepId: 'verify_written_file',
        name: 'Verify File Exists on Disk',
        stepType: 'VERIFY',
        dependencies: ['write_file'],
        verification: {
          type: 'file_exists',
          target: 'path',
        },
        timeoutMs: 10000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['filesystem'],
      requiredTools: ['file_write'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 6. verify-file
  {
    id: 'builtin-verify-file',
    name: 'verify-file',
    displayName: 'Verify File Invariant',
    description: 'Verifies existence and contents of a workspace file without side-effects.',
    category: 'OPERATIONS',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['verify file', 'check file exists', 'validate file'],
    requiredCapabilities: ['filesystem'],
    requiredTools: ['file_read'],
    inputsSchema: {
      type: 'object',
      properties: {
        path: { type: 'string' },
      },
      required: ['path'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        exists: { type: 'boolean' },
        sizeBytes: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'verify_existence',
        name: 'Verify File Existence',
        stepType: 'VERIFY',
        dependencies: [],
        verification: {
          type: 'file_exists',
          target: 'path',
        },
        timeoutMs: 10000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['filesystem'],
      requiredTools: ['file_read'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 7. summarize-document
  {
    id: 'builtin-summarize-document',
    name: 'summarize-document',
    displayName: 'Summarize Document',
    description: 'Reads an authorized local text or markdown document and produces a structured summary.',
    category: 'DOCUMENT',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['summarize document', 'summarize file', 'create summary'],
    requiredCapabilities: ['filesystem', 'document'],
    requiredTools: ['file_read'],
    inputsSchema: {
      type: 'object',
      properties: {
        documentPath: { type: 'string' },
      },
      required: ['documentPath'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        summary: { type: 'string' },
        wordCount: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'read_doc',
        name: 'Read Document Content',
        stepType: 'TOOL',
        tool: 'file_read',
        dependencies: [],
        timeoutMs: 30000,
      },
      {
        stepIndex: 1,
        stepId: 'summarize_content',
        name: 'Extract Key Summary',
        stepType: 'MODEL',
        dependencies: ['read_doc'],
        timeoutMs: 60000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['filesystem', 'document'],
      requiredTools: ['file_read'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 8. investigate-error
  {
    id: 'builtin-investigate-error',
    name: 'investigate-error',
    displayName: 'Investigate Runtime Error',
    description: 'Analyzes error messages, traces stack traces to source files, and identifies remediation steps.',
    category: 'SOFTWARE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['investigate error', 'debug error', 'fix failure', 'analyze crash'],
    requiredCapabilities: ['code-analysis', 'filesystem'],
    requiredTools: ['file_read'],
    inputsSchema: {
      type: 'object',
      properties: {
        errorMessage: { type: 'string' },
        stackTrace: { type: 'string' },
      },
      required: ['errorMessage'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        rootCause: { type: 'string' },
        suggestedFix: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'parse_error',
        name: 'Parse Error Stack Trace',
        stepType: 'DETERMINISTIC',
        dependencies: [],
        timeoutMs: 15000,
      },
      {
        stepIndex: 1,
        stepId: 'inspect_culprit_file',
        name: 'Read Culprit Source File',
        stepType: 'TOOL',
        tool: 'file_read',
        dependencies: ['parse_error'],
        timeoutMs: 30000,
      },
      {
        stepIndex: 2,
        stepId: 'remediation_analysis',
        name: 'Synthesize Remediation Steps',
        stepType: 'MODEL',
        dependencies: ['inspect_culprit_file'],
        timeoutMs: 60000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['code-analysis', 'filesystem'],
      requiredTools: ['file_read'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // INT-005 Built-in Research Skills
  // 9. research-topic
  {
    id: 'builtin-research-topic',
    name: 'research-topic',
    displayName: 'Research Topic Intelligence',
    description: 'Investigates a topic across multi-source web intelligence, extracts claims, and produces bounded synthesis.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['research topic', 'investigate topic', 'gather intelligence on', 'deep research'],
    requiredCapabilities: ['web.research', 'source.extraction', 'evidence.synthesis'],
    requiredTools: ['research.execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        topic: { type: 'string' },
        depth: { type: 'string', enum: ['QUICK', 'NORMAL', 'DEEP', 'COMPREHENSIVE'], default: 'NORMAL' },
      },
      required: ['topic'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        studyId: { type: 'string' },
        synthesis: { type: 'string' },
        sourcesCount: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'execute_research',
        name: 'Execute Multi-Source Research',
        stepType: 'TOOL',
        tool: 'research.execute',
        dependencies: [],
        inputs: { topic: '{{inputs.topic}}', depth: '{{inputs.depth}}' },
        timeoutMs: 120000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web.research'],
      requiredTools: ['research.execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 10. compare-sources
  {
    id: 'builtin-compare-sources',
    name: 'compare-sources',
    displayName: 'Compare Sources & Discrepancies',
    description: 'Cross-analyzes multiple sources on a topic to highlight corroborations, contradictions, and version differences.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['compare sources', 'cross source analysis', 'compare evidence', 'source discrepancy check'],
    requiredCapabilities: ['web.research', 'source.extraction'],
    requiredTools: ['research.execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        topic: { type: 'string' },
      },
      required: ['topic'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        synthesis: { type: 'string' },
        contradictionsFound: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'compare_execution',
        name: 'Execute Comparison Research',
        stepType: 'TOOL',
        tool: 'research.execute',
        dependencies: [],
        inputs: { topic: '{{inputs.topic}}', researchType: 'COMPARISON', depth: 'NORMAL' },
        timeoutMs: 120000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web.research'],
      requiredTools: ['research.execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 11. verify-claim
  {
    id: 'builtin-verify-claim',
    name: 'verify-claim',
    displayName: 'Verify Claim Factuality',
    description: 'Investigates a specific factual claim against reliable web sources to corroborate or refute it.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['verify claim', 'fact check', 'verify whether true', 'check factuality'],
    requiredCapabilities: ['web.research'],
    requiredTools: ['research.execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        claim: { type: 'string' },
      },
      required: ['claim'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        verified: { type: 'boolean' },
        synthesis: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'verify_execution',
        name: 'Execute Claim Verification Research',
        stepType: 'TOOL',
        tool: 'research.execute',
        dependencies: [],
        inputs: { topic: '{{inputs.claim}}', researchType: 'VERIFICATION', depth: 'NORMAL' },
        timeoutMs: 120000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web.research'],
      requiredTools: ['research.execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 12. investigate-company
  {
    id: 'builtin-investigate-company',
    name: 'investigate-company',
    displayName: 'Investigate Company Intelligence',
    description: 'Gathers corporate intelligence, leadership, products, funding, and market positioning for a company.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['investigate company', 'company intelligence', 'startup research', 'corporate background'],
    requiredCapabilities: ['web.research'],
    requiredTools: ['research.execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        company: { type: 'string' },
      },
      required: ['company'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        synthesis: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'company_execution',
        name: 'Execute Company Research',
        stepType: 'TOOL',
        tool: 'research.execute',
        dependencies: [],
        inputs: { topic: '{{inputs.company}}', researchType: 'COMPANY_RESEARCH', depth: 'NORMAL' },
        timeoutMs: 120000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web.research'],
      requiredTools: ['research.execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 13. technical-research
  {
    id: 'builtin-technical-research',
    name: 'technical-research',
    displayName: 'Deep Technical Architecture Research',
    description: 'Investigates technical specifications, architectural patterns, benchmarks, and protocols.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['technical research', 'architecture investigation', 'protocol specs', 'technical deep dive'],
    requiredCapabilities: ['web.research'],
    requiredTools: ['research.execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        topic: { type: 'string' },
      },
      required: ['topic'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        synthesis: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'tech_execution',
        name: 'Execute Technical Research',
        stepType: 'TOOL',
        tool: 'research.execute',
        dependencies: [],
        inputs: { topic: '{{inputs.topic}}', researchType: 'TECHNICAL_RESEARCH', depth: 'DEEP' },
        timeoutMs: 180000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web.research'],
      requiredTools: ['research.execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 14. open-source-research
  {
    id: 'builtin-open-source-research',
    name: 'open-source-research',
    displayName: 'Open Source Ecosystem Research',
    description: 'Identifies, evaluates, and compares open-source repositories, libraries, licenses, and maintainer activity.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_1',
    triggerPhrases: ['open source research', 'find github repositories', 'open source alternative', 'oss library research'],
    requiredCapabilities: ['web.research'],
    requiredTools: ['research.execute'],
    inputsSchema: {
      type: 'object',
      properties: {
        query: { type: 'string' },
      },
      required: ['query'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        synthesis: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'oss_execution',
        name: 'Execute Open Source Ecosystem Research',
        stepType: 'TOOL',
        tool: 'research.execute',
        dependencies: [],
        inputs: { topic: '{{inputs.query}}', researchType: 'OPEN_SOURCE_RESEARCH', depth: 'NORMAL' },
        timeoutMs: 120000,
      },
    ],
    permissions: {
      maxDangerTier: 1,
      requiredCapabilities: ['web.research'],
      requiredTools: ['research.execute'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 15. knowledge-search
  {
    id: 'builtin-knowledge-search',
    name: 'knowledge-search',
    displayName: 'Search Sovereign Knowledge Graph',
    description: 'Searches entities, concepts, relationships, and structured facts in the sovereign Knowledge Graph.',
    category: 'DATA',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['search knowledge', 'find in knowledge graph', 'query knowledge base', 'knowledge search'],
    requiredCapabilities: ['knowledge.query'],
    requiredTools: ['knowledge.search'],
    inputsSchema: {
      type: 'object',
      properties: {
        query: { type: 'string' },
      },
      required: ['query'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        entities: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'search_entities',
        name: 'Query Knowledge Entities',
        stepType: 'TOOL',
        tool: 'knowledge.search',
        dependencies: [],
        inputs: { query: '{{inputs.query}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['knowledge.query'],
      requiredTools: ['knowledge.search'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 16. entity-resolve
  {
    id: 'builtin-entity-resolve',
    name: 'entity-resolve',
    displayName: 'Resolve Knowledge Entity & Aliases',
    description: 'Resolves ambiguous entity names, script variants, and aliases to canonical knowledge entities.',
    category: 'DATA',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['resolve entity', 'lookup alias', 'canonical entity', 'entity lookup'],
    requiredCapabilities: ['knowledge.lookup'],
    requiredTools: ['knowledge.entity.lookup'],
    inputsSchema: {
      type: 'object',
      properties: {
        entityIdOrName: { type: 'string' },
      },
      required: ['entityIdOrName'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        entity: { type: 'object' },
        neighbors: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'resolve_lookup',
        name: 'Resolve Entity Details',
        stepType: 'TOOL',
        tool: 'knowledge.entity.lookup',
        dependencies: [],
        inputs: { entityIdOrName: '{{inputs.entityIdOrName}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['knowledge.lookup'],
      requiredTools: ['knowledge.entity.lookup'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 17. fact-verify
  {
    id: 'builtin-fact-verify',
    name: 'fact-verify',
    displayName: 'Verify Evidence-Backed Facts',
    description: 'Queries verified, evidence-backed facts from the sovereign Knowledge Graph.',
    category: 'DATA',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['verify fact', 'check knowledge fact', 'query verified fact', 'fact check graph'],
    requiredCapabilities: ['knowledge.facts'],
    requiredTools: ['knowledge.fact.query'],
    inputsSchema: {
      type: 'object',
      properties: {
        predicate: { type: 'string' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        facts: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'query_facts',
        name: 'Query Verified Facts',
        stepType: 'TOOL',
        tool: 'knowledge.fact.query',
        dependencies: [],
        inputs: { predicate: '{{inputs.predicate}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['knowledge.facts'],
      requiredTools: ['knowledge.fact.query'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 18. decision-recall
  {
    id: 'builtin-decision-recall',
    name: 'decision-recall',
    displayName: 'Recall Architectural & Strategic Decisions',
    description: 'Recalls decisions, rationale, alternatives considered, scope, and provenance.',
    category: 'DATA',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['recall decision', 'why did we choose', 'architectural decisions', 'decision rationale'],
    requiredCapabilities: ['knowledge.facts'],
    requiredTools: ['knowledge.fact.query'],
    inputsSchema: {
      type: 'object',
      properties: {
        predicate: { type: 'string', default: 'decision' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        facts: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'query_decisions',
        name: 'Query Decision Facts',
        stepType: 'TOOL',
        tool: 'knowledge.fact.query',
        dependencies: [],
        inputs: { predicate: '{{inputs.predicate}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['knowledge.facts'],
      requiredTools: ['knowledge.fact.query'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 19. project-knowledge-search
  {
    id: 'builtin-project-knowledge-search',
    name: 'project-knowledge-search',
    displayName: 'Project Knowledge Isolation Search',
    description: 'Performs isolated knowledge retrieval scoped to a specific project.',
    category: 'DATA',
    owner: 'SYSTEM',
    scope: 'PROJECT',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['project knowledge', 'search project graph', 'project dependencies', 'project tech stack'],
    requiredCapabilities: ['knowledge.query'],
    requiredTools: ['knowledge.search'],
    inputsSchema: {
      type: 'object',
      properties: {
        query: { type: 'string' },
      },
      required: ['query'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        entities: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'search_project_entities',
        name: 'Search Project Entities',
        stepType: 'TOOL',
        tool: 'knowledge.search',
        dependencies: [],
        inputs: { query: '{{inputs.query}}', scope: 'PROJECT' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['knowledge.query'],
      requiredTools: ['knowledge.search'],
      requiresHumanApproval: false,
      allowedScopes: ['PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 20. research-knowledge-link
  {
    id: 'builtin-research-knowledge-link',
    name: 'research-knowledge-link',
    displayName: 'Research Knowledge Linkage',
    description: 'Queries facts and evidence linked to completed research studies.',
    category: 'DATA',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['research knowledge link', 'study evidence', 'facts from research', 'citations graph'],
    requiredCapabilities: ['knowledge.facts'],
    requiredTools: ['knowledge.fact.query'],
    inputsSchema: {
      type: 'object',
      properties: {
        subjectEntityId: { type: 'string' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        facts: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'query_research_facts',
        name: 'Query Research Facts',
        stepType: 'TOOL',
        tool: 'knowledge.fact.query',
        dependencies: [],
        inputs: { subjectEntityId: '{{inputs.subjectEntityId}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['knowledge.facts'],
      requiredTools: ['knowledge.fact.query'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 21. context-search
  {
    id: 'builtin-context-search',
    name: 'context-search',
    displayName: 'Cognitive Context Search',
    description: 'Searches across unified memory, decisions, and knowledge graph using the cognitive ranker.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['context search', 'search context', 'cognitive search', 'find relevant context'],
    requiredCapabilities: ['context.search'],
    requiredTools: ['context.search'],
    inputsSchema: {
      type: 'object',
      properties: {
        query: { type: 'string' },
        limit: { type: 'number', default: 10 },
      },
      required: ['query'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        items: { type: 'array' },
        totalFound: { type: 'number' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'search_context',
        name: 'Search Cognitive Context',
        stepType: 'TOOL',
        tool: 'context.search',
        dependencies: [],
        inputs: { query: '{{inputs.query}}', limit: '{{inputs.limit}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['context.search'],
      requiredTools: ['context.search'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY', 'CREATOR'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 22. decision-context
  {
    id: 'builtin-decision-context',
    name: 'decision-context',
    displayName: 'Decision & Architecture Context',
    description: 'Retrieves architectural decisions, rationale, alternatives, and superseded states for a project.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'PROJECT',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['decision context', 'why did we choose', 'architecture decision', 'decision rationale'],
    requiredCapabilities: ['context.inspect'],
    requiredTools: ['context.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        userMessage: { type: 'string' },
        projectId: { type: 'string' },
      },
      required: ['userMessage'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        selectedCandidates: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'inspect_decision_context',
        name: 'Inspect Decision Context',
        stepType: 'TOOL',
        tool: 'context.inspect',
        dependencies: [],
        inputs: { userMessage: '{{inputs.userMessage}}', projectId: '{{inputs.projectId}}', intent: 'DECISION_QUERY' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['context.inspect'],
      requiredTools: ['context.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['PROJECT', 'GLOBAL'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 23. project-context
  {
    id: 'builtin-project-context',
    name: 'project-context',
    displayName: 'Project Scoped Context',
    description: 'Assembles project-isolated context preventing cross-project knowledge leakage.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'PROJECT',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['project context', 'project details', 'project knowledge', 'isolated project context'],
    requiredCapabilities: ['context.inspect'],
    requiredTools: ['context.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        userMessage: { type: 'string' },
        projectId: { type: 'string' },
      },
      required: ['userMessage', 'projectId'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        selectedCandidates: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'assemble_project_context',
        name: 'Assemble Project Context',
        stepType: 'TOOL',
        tool: 'context.inspect',
        dependencies: [],
        inputs: { userMessage: '{{inputs.userMessage}}', projectId: '{{inputs.projectId}}', intent: 'PROJECT_QUERY' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['context.inspect'],
      requiredTools: ['context.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 24. company-context
  {
    id: 'builtin-company-context',
    name: 'company-context',
    displayName: 'Company Scoped Context',
    description: 'Retrieves company-scoped operational context, departments, goals, and metrics.',
    category: 'BUSINESS',
    owner: 'SYSTEM',
    scope: 'COMPANY',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['company context', 'company details', 'company operational context'],
    requiredCapabilities: ['context.inspect'],
    requiredTools: ['context.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        userMessage: { type: 'string' },
        companyId: { type: 'string' },
      },
      required: ['userMessage', 'companyId'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        selectedCandidates: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'assemble_company_context',
        name: 'Assemble Company Context',
        stepType: 'TOOL',
        tool: 'context.inspect',
        dependencies: [],
        inputs: { userMessage: '{{inputs.userMessage}}', companyId: '{{inputs.companyId}}', intent: 'COMPANY_QUERY' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['context.inspect'],
      requiredTools: ['context.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['COMPANY'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 25. evidence-context
  {
    id: 'builtin-evidence-context',
    name: 'evidence-context',
    displayName: 'Evidence & Research Context',
    description: 'Retrieves verified research claims, citations, and evidence for technical or factual inquiries.',
    category: 'RESEARCH',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['evidence context', 'research evidence', 'verified claims', 'citations context'],
    requiredCapabilities: ['context.inspect'],
    requiredTools: ['context.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        userMessage: { type: 'string' },
      },
      required: ['userMessage'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        selectedCandidates: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'assemble_evidence_context',
        name: 'Assemble Evidence Context',
        stepType: 'TOOL',
        tool: 'context.inspect',
        dependencies: [],
        inputs: { userMessage: '{{inputs.userMessage}}', intent: 'RESEARCH_QUERY' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['context.inspect'],
      requiredTools: ['context.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 26. knowledge-context
  {
    id: 'builtin-knowledge-context',
    name: 'knowledge-context',
    displayName: 'Knowledge Graph Context',
    description: 'Traverses entity relationships and verified facts within bounded distance for contextual enrichment.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['knowledge context', 'graph context', 'entity facts context', 'relationship context'],
    requiredCapabilities: ['context.inspect'],
    requiredTools: ['context.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        userMessage: { type: 'string' },
      },
      required: ['userMessage'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        selectedCandidates: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'assemble_knowledge_context',
        name: 'Assemble Knowledge Context',
        stepType: 'TOOL',
        tool: 'context.inspect',
        dependencies: [],
        inputs: { userMessage: '{{inputs.userMessage}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['context.inspect'],
      requiredTools: ['context.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY', 'CREATOR'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 27. working-context
  {
    id: 'builtin-working-context',
    name: 'working-context',
    displayName: 'Inspect Working Context',
    description: 'Inspects and assembles active working memory, current task, blockers, and continuity state.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['working context', 'active continuity', 'current working memory', 'show working context'],
    requiredCapabilities: ['working_memory.inspect'],
    requiredTools: ['working_memory.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        activeProject: { type: 'string' },
        activeTask: { type: 'string' },
        blockers: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'inspect_working_memory',
        name: 'Inspect Working Memory State',
        stepType: 'TOOL',
        tool: 'working_memory.inspect',
        dependencies: [],
        inputs: { sessionId: '{{inputs.sessionId}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['working_memory.inspect'],
      requiredTools: ['working_memory.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'COMPANY', 'SESSION'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 28. resume-task
  {
    id: 'builtin-resume-task',
    name: 'resume-task',
    displayName: 'Resume Conversational Task',
    description: 'Recovers unfinished task, active blocker, and next recommended step from active working memory.',
    category: 'WORKFLOW',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['resume task', 'continue previous work', 'pick up task', 'what was i working on'],
    requiredCapabilities: ['working_memory.inspect'],
    requiredTools: ['working_memory.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        activeTask: { type: 'string' },
        blockers: { type: 'array' },
        nextSteps: { type: 'array' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'inspect_task_continuation',
        name: 'Inspect Task State',
        stepType: 'TOOL',
        tool: 'working_memory.inspect',
        dependencies: [],
        inputs: { sessionId: '{{inputs.sessionId}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['working_memory.inspect'],
      requiredTools: ['working_memory.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'SESSION'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 29. conversation-checkpoint
  {
    id: 'builtin-conversation-checkpoint',
    name: 'conversation-checkpoint',
    displayName: 'Inspect Conversation Checkpoints',
    description: 'Inspects and lists conversation checkpoints for multi-session resumption and restart recovery.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['inspect checkpoint', 'list checkpoints', 'view checkpoints', 'checkpoints'],
    requiredCapabilities: ['working_memory.checkpoint'],
    requiredTools: ['working_memory.checkpoint'],
    inputsSchema: {
      type: 'object',
      properties: {
        sessionId: { type: 'string' },
        action: { type: 'string', default: 'INSPECT_LATEST' },
      },
    },
    outputsSchema: {
      type: 'object',
      properties: {
        checkpoint: { type: 'object' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'inspect_checkpoint',
        name: 'Inspect Checkpoint',
        stepType: 'TOOL',
        tool: 'working_memory.checkpoint',
        dependencies: [],
        inputs: { sessionId: '{{inputs.sessionId}}', action: '{{inputs.action}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['working_memory.checkpoint'],
      requiredTools: ['working_memory.checkpoint'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'SESSION'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },

  // 30. resolve-reference
  {
    id: 'builtin-resolve-reference',
    name: 'resolve-reference',
    displayName: 'Resolve Conversational Reference',
    description: 'Resolves anaphoric expressions and pronouns to active working memory concepts with ambiguity detection.',
    category: 'INTELLIGENCE',
    owner: 'SYSTEM',
    scope: 'GLOBAL',
    status: 'ACTIVE',
    version: '1.0.0',
    riskLevel: 'TIER_0',
    triggerPhrases: ['resolve reference', 'what does it refer to', 'resolve pronoun', 'disambiguate reference'],
    requiredCapabilities: ['working_memory.inspect'],
    requiredTools: ['working_memory.inspect'],
    inputsSchema: {
      type: 'object',
      properties: {
        userMessage: { type: 'string' },
        sessionId: { type: 'string' },
      },
      required: ['userMessage'],
    },
    outputsSchema: {
      type: 'object',
      properties: {
        resolved: { type: 'boolean' },
        concept: { type: 'string' },
      },
    },
    steps: [
      {
        stepIndex: 0,
        stepId: 'inspect_for_reference',
        name: 'Inspect Working State for Resolution',
        stepType: 'TOOL',
        tool: 'working_memory.inspect',
        dependencies: [],
        inputs: { sessionId: '{{inputs.sessionId}}' },
        timeoutMs: 15000,
      },
    ],
    permissions: {
      maxDangerTier: 0,
      requiredCapabilities: ['working_memory.inspect'],
      requiredTools: ['working_memory.inspect'],
      requiresHumanApproval: false,
      allowedScopes: ['GLOBAL', 'PROJECT', 'SESSION'],
    },
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  ...ENGINEERING_SKILLS,
];
